"""add daily_pnl table

Revision ID: b033178c02bc
Revises: 
Create Date: 2026-03-04 20:05:05.439874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b033178c02bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_pnl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_value', sa.Float(), nullable=True),
    sa.Column('close_value', sa.Float(), nullable=True),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('daily_pnl_pct', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('total_fees', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('buy_count', sa.Integer(), nullable=True),
    sa.Column('sell_count', sa.Integer(), nullable=True),
    sa.Column('win_count', sa.Integer(), nullable=True),
    sa.Column('loss_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'date', name='uq_daily_pnl_exchange_date')
    )
    op.create_index('ix_daily_pnl_exchange_date', 'daily_pnl', ['exchange', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_pnl_exchange_date', table_name='daily_pnl')
    op.drop_table('daily_pnl')
    # ### end Alembic commands ###
